"""Initial

Revision ID: 4e944ec452e7
Revises: 
Create Date: 2025-05-02 19:43:13.721502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e944ec452e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles_detected',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('original_plate', sa.String(), nullable=True),
    sa.Column('correct_plate', sa.String(), nullable=True),
    sa.Column('valid_plate', sa.String(), nullable=True),
    sa.Column('xmin', sa.Integer(), nullable=True),
    sa.Column('ymin', sa.Integer(), nullable=True),
    sa.Column('xmax', sa.Integer(), nullable=True),
    sa.Column('ymax', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_path', 'original_plate', name='unique_image_plate_constraint')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles_detected')
    # ### end Alembic commands ###
